export const GET_STRIPE_APIKEY_REQUEST = 'GET_STRIPE_APIKEY_REQUEST';
export const GET_STRIPE_APIKEY_SUCCESS = 'GET_STRIPE_APIKEY_SUCCESS';
export const GET_STRIPE_APIKEY_FAILED = 'GET_STRIPE_APIKEY_FAILED';

export const PROCESS_PAYMENT_REQUEST = 'PROCESS_PAYMENT_REQUEST';
export const PROCESS_PAYMENT_SUCCESS = 'PROCESS_PAYMENT_SUCCESS';
export const PROCESS_PAYMENT_FAILED = 'PROCESS_PAYMENT_FAILED';
export const PROCESS_PAYMENT_RESET = 'PROCESS_PAYMENT_RESET';
