export const CREATE_FLASHSALE_REQUEST = 'CREATE_FLASHSALE_REQUEST'
export const CREATE_FLASHSALE_SUCCESS = 'CREATE_FLASHSALE_SUCCESS'
export const CREATE_FLASHSALE_FAIL = 'CREATE_FLASHSALE_FAIL'

export const MY_FLASHSALES_REQUEST = 'MY_FLASHSALES_REQUEST'
export const MY_FLASHSALES_SUCCESS = 'MY_FLASHSALES_SUCCESS'
export const MY_FLASHSALES_FAIL = 'MY_FLASHSALES_FAIL'

export const ALL_FLASHSALES_REQUEST = 'ALL_FLASHSALES_REQUEST'
export const ALL_FLASHSALES_SUCCESS = 'ALL_FLASHSALES_SUCCESS'
export const ALL_FLASHSALES_FAIL = 'ALL_FLASHSALES_FAIL'

export const UPDATE_FLASHSALE_REQUEST = 'UPDATE_FLASHSALE_REQUEST'
export const UPDATE_FLASHSALE_SUCCESS = 'UPDATE_FLASHSALE_SUCCESS'
export const UPDATE_FLASHSALE_RESET = 'UPDATE_FLASHSALE_RESET'
export const UPDATE_FLASHSALE_FAIL = 'UPDATE_FLASHSALE_FAIL'

export const DELETE_FLASHSALE_REQUEST = 'DELETE_FLASHSALE_REQUEST'
export const DELETE_FLASHSALE_SUCCESS = 'DELETE_FLASHSALE_SUCCESS'
export const DELETE_FLASHSALE_RESET = 'DELETE_FLASHSALE_RESET'
export const DELETE_FLASHSALE_FAIL = 'DELETE_FLASHSALE_FAIL'

export const FLASHSALE_DETAILS_REQUEST = 'FLASHSALE_DETAILS_REQUEST'
export const FLASHSALE_DETAILS_SUCCESS = 'FLASHSALE_DETAILS_SUCCESS'
export const FLASHSALE_DETAILS_FAIL = 'FLASHSALE_DETAILS_FAIL'

export const CLEAR_ERROR = 'CLEAR_ERROR'