export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAILED = 'ALL_PRODUCTS_FAILED';

export const BEST_SELLERS_REQUEST = 'BEST_SELLERS_REQUEST';
export const BEST_SELLERS_SUCCESS = 'BEST_SELLERS_SUCCESS';
export const BEST_SELLERS_FAILED = 'BEST_SELLERS_FAILED';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED';

export const CHECK_IS_BUY_REQUEST = 'CHECK_IS_BUY_REQUEST';
export const CHECK_IS_BUY_SUCCESS = 'CHECK_IS_BUY_SUCCESS';
export const CHECK_IS_BUY_FAILED = 'CHECK_IS_BUY_FAILED';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
export const NEW_REVIEW_FAILED = 'NEW_REVIEW_FAILED';

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILED = 'GET_REVIEWS_FAILED';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET';
export const DELETE_REVIEW_FAILED = 'DELETE_REVIEW_FAILED';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
